version: "3"
services:
  qili.proxy:
    image: nginx:1.9.3
    ports:
    - "80"
    - "443"
    links:
    - qili.server
    volumes:
    - "c:/work/spool/qili/data:/data"
    - "c:/work/spool/qili/deploy/nginx.conf:/etc/nginx/nginx.conf"
  qili.db:
    image: mongo:3.1
    volumes:
    - c:/work/spool/qili/data/mongo:/data/db
    command: --storageEngine=wiredTiger --directoryperdb
    ports:
    - "27017"
  qili.server:
    image: node:8-alpine
    links: 
    - qili.db
    volumes:
    - "c:/work/spool/qili:/app"
    working_dir: /app
    ports:
    - "9080"
    environment:
    - DOMAIN
    - DB_HOST
    - DB_PORT
    - APPS_ROOT
    - ADMIN_KEY
    - SECRET
    - ROOT
    - ROOT_PASSWORD
    - QINIU_ACCESS_KEY
    - QINIU_SECRET_KEY
    - QINIU_BUCKET
    - QINIU_ACCESS_URL
    - ALI_ACCESS_KEY
    - ALI_SECRET_KEY
    - ALI_SMS_SIGN_NAME=papazai网
    - ALI_SMS_TEMPLATE_RESET
    - ALI_SMS_TEMPLATE_CREATE
    - DEBUG
    - CLOUD_TIMEOUT
    - WECHAT_TOKEN